default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: n2me
  password: n2me
  host: localhost
  
development:
  <<: *default
  database: n2me_dev

test:
  <<: *default
  database: n2me_test

